/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./../../src/components/AboutSection.vue')['default']
    ButtonElement: typeof import('./../../src/components/elements/ButtonElement.vue')['default']
    CardElement: typeof import('./../../src/components/elements/CardElement.vue')['default']
    CardLink: typeof import('./../../src/components/elements/CardLink.vue')['default']
    ContactSection: typeof import('./../../src/components/ContactSection.vue')['default']
    FooterSection: typeof import('./../../src/components/FooterSection.vue')['default']
    FormInput: typeof import('./../../src/components/forms/FormInput.vue')['default']
    HeroSection: typeof import('./../../src/components/HeroSection.vue')['default']
    HomerSection: typeof import('./../../src/components/HomerSection.vue')['default']
    NavbarSection: typeof import('./../../src/components/NavbarSection.vue')['default']
    ProjectsSection: typeof import('./../../src/components/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineElement: typeof import('./../../src/components/elements/TimelineElement.vue')['default']
  }
}
