/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./../components/AboutSection.vue')['default']
    ButtonElement: typeof import('./../components/elements/ButtonElement.vue')['default']
    CardElement: typeof import('./../components/elements/CardElement.vue')['default']
    CardLink: typeof import('./../components/elements/CardLink.vue')['default']
    ContactSection: typeof import('./../components/ContactSection.vue')['default']
    FooterSection: typeof import('./../components/FooterSection.vue')['default']
    FormInput: typeof import('./../components/forms/FormInput.vue')['default']
    HeroSection: typeof import('./../components/HeroSection.vue')['default']
    HomerSection: typeof import('./../components/HomerSection.vue')['default']
    NavbarSection: typeof import('./../components/NavbarSection.vue')['default']
    ProjectsSection: typeof import('./../components/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineElement: typeof import('./../components/elements/TimelineElement.vue')['default']
  }
}
